on:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install && npx playwright install
        

      - name: Wait Netlify
        uses: denar90/wait-for-netlify-action@v2.0.2
        id: waitForNetlify
        with:
          site_id: "c3f4d793-1fca-4854-934a-bfde3b597a6b"
          
      - name: Run playwright tests
        run: npm test
        env:
          DEPLOY_URL: ${{ steps.wait-for-netflify.outputs.url }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: test-results   
