on:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install && npx playwright install &&  npm test
        

      - name: Waiting for Netlify deploy
        uses: mskelton/wait-for-netlify-action@v1
        id: wait-for-netflify
        with:
          site_name: https://jade-pastelito-936508.netlify.app/
      - run: npm test
        env:
          DEPLOY_URL: ${{ steps.wait-for-netflify.outputs.url }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: test-results   
